### PR TITLE
Fix for localized versions of IE11

### PR DESCRIPTION
**Pull request by excentrik**
Address #27 by checking for specific error number match

### CODE REVIEW

**Comment by chrisbolin** [comment]
Thanks!

**Comment by boygirl** [comment]
@chrisbolin does this need additional verification to merge?

**Comment by chrisbolin** [comment]
merged! thanks for the nudge @boygirl :) i'll make a build tomorrow. i'll also make an issue for this to investigate catching the error in other browsers.

**Comment by chrisbolin** [comment]
released in `react-fast-compare@2.0.2`

**Pull request merged**
