### PR TITLE
fix react-native bug for DOM "Element" checking

### PR DESCRIPTION
**Pull request by chrisbolin**
Fix for #38

### CODE REVIEW

**Comment by pgom** [comment]
💪

**Comment by chrisbolin** [comment]
Fix doesn't work on IE. I'm guessing `Element` is not a `function` on IE. It's probably easier to test on AppVeyor in CI than to get a VM with IE (not Edge!) up and running. Will do this now

**Comment by pgom** [comment]
What about just check if `typeof(Element) != undefined`?

**Comment by chrisbolin** [comment]
nice when a theory works out. So Element is `typeof` `"object"` in IE. Will change this and retest

**Pull request merged**
